### ISSUE TITLE
Simpler CURIE prefix expansion is broken

### ISSUE THREAD

**Issue by jdr0887** [NCATS-Tangerine/cam-kp-api#126]
Looks like IRI's with a fully expanded URL (eg, http://purl.obolibrary.org/obo/GO_0005829) have their prefix removed & re-added without the ":".  So, as written, an IRI with a value of "http://purl.obolibrary.org/obo/GO_0005829" will get transformed into "http//purl.obolibrary.org/obo/GO_0005829" when decoded from JSON.  If the IRI value is collapsed (eg, NCBIGene:558), then it gets transformed properly into "http://www.ncbi.nlm.nih.gov/gene/558".  I think the following line needs to have a ":" added to it.

https://github.com/NCATS-Tangerine/cam-kp-api/blob/ec9256813e0a516924273ddbaafc4c43c200950d/src/main/scala/org/renci/cam/Implicits.scala#L19

**Comment by balhoff** [comment]
D'oh!
