### ISSUE TITLE
clean up queryEdgePredicates return values and their use in call site

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#131]
I think the values are not really needed in their current structure; it's working but something got garbled in refactoring.

**Comment by jdr0887** [comment]
I ran the tests after making this change and noticed that wormbase in our prefixes doesn't match that of the database.  Found "http://identifiers.org/wormbase/WBGene00000245", but should be "https://www.wormbase.org/get?name=WBGene00000245", right?

**Comment by balhoff** [comment]
Thanks, I made an issue here: https://github.com/biolink/biolink-model/issues/530
