### ISSUE TITLE
Implement TRAPI 1.0 spec

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#165]
We need to get this done ASAP. @jdr0887 is already working on it.

**Comment by balhoff** [comment]
We now have a working version, but we need to review the spec to make sure we have everything right in the node and edge bindings area. Some values may need to be enclosed within arrays.

**Comment by balhoff** [comment]
@jdr0887 can we close this one?

**Comment by jdr0887** [comment]
Yes, this can be closed.
