### ISSUE TITLE
Map IRIs with WBGene namespace into biolink model

### ISSUE THREAD

**Issue by rajshruti18** [NCATS-Tangerine/cam-kp-api#199]
Some examples of unmapped WBGene IRIs:
```
http://identifiers.org/wormbase/WBGene00013878
http://identifiers.org/wormbase/WBGene00017920
http://identifiers.org/wormbase/WBGene00000467

```

**Comment by rajshruti18** [comment]
There is a prefix for wormbase but not WBGene specifically. Look here: https://github.com/biolink/biolink-model/blob/master/context.jsonld#L172

**Comment by balhoff** [comment]
We need to add a feature to the web service app that can normalize IRIs to a canonical namespace before compacting to a CURIE using the biolink-model context. For example, when constructing a return message:

  1. Rewrite `http://identifiers.org/wormbase/WBGene00013878` to `https://identifiers.org/wb/WBGene00013878`.
  2. Compact `https://identifiers.org/wb/WBGene00013878` to `WB:WBGene00013878`
