### ISSUE TITLE
Map IRIs with ncbigene namespace into biolink model

### ISSUE THREAD

**Issue by rajshruti18** [NCATS-Tangerine/cam-kp-api#201]
Some examples are:
```
http://identifiers.org/ncbigene:1482
http://identifiers.org/ncbigene:25948
http://identifiers.org/ncbigene:2626
```

**Comment by rajshruti18** [comment]
There is a prefix for ncbigene but the format seems different. Look here: https://github.com/biolink/biolink-model/blob/master/context.jsonld#L96. **context.jsonld** has a '/' instead of ':'

**Comment by balhoff** [comment]
This was fixed in the pipeline.
