### ISSUE TITLE
meta_knowledge_graph format

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/cam-kp-api#281]
The /meta_knowledge_graph output appears to be strangely formatted. The value for the "nodes" key appears to be a dict with key "id_prefixes" whose value is a list of URI prefixes. We want these to be CURIE prefixes according to biolink (e.g. "OMIM" instead of "http://purl.obolibrary.org/obo/OMIM_"), and we want the "id_prefixes" to be nested under keys for each biolink category e.g. "biolink:ChemicalSubstance", so that we can identify the proper prefixes on a per-category basis.

Example:
```json
{"nodes": {
    "biolink:ChemicalSubstance": {"id_prefixes": ["CHEBI", "PUBCHEM.COMPOUND"]},
    ...
}}
```

**Comment by jdr0887** [comment]
This should be resolved with the latest deployment I made moments ago.  @patrickkwang Can you verify this is what you expected?

https://cam-kp-api-dev.renci.org/meta_knowledge_graph

**Comment by patrickkwang** [comment]
Looks good!
