### ISSUE TITLE
Pathway-> Standup query

### ISSUE THREAD

**Issue by cbizon** [NCATS-Tangerine/cam-kp-api#282]
Standup issue:

https://github.com/NCATSTranslator/testing/issues/64

https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.1/genePathway.json

CAM-KP is returning some results, but they don't seem on point (i.e. they don't match the input reactome )

**Comment by balhoff** [comment]
I'm surprised it's returning anything. `http://www.reactome.org/PathwayBrowser/#/R-HSA-909733` is not used in our database. @jdr0887 could you investigate why we would return any results?

**Comment by balhoff** [comment]
@cbizon I suspect the issue here is that you were submitting this query to the TRAPI 1.0 endpoint, which doesn't recognize the constraints in the 1.1 format. In our 1.1 endpoint this query returns nothing.
