### ISSUE TITLE
consider overriding NCBIGENE prefix coming from Biolink

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#301]
This issue https://github.com/biolink/biolink-model/issues/725 is causing many problems, because the rest of Translator continues to use `NCBIGene`. We rely on the Biolink context file, which uses `NCBIGENE`. This hasn't been changed in the new Biolink-model 2.0 release. We might need to special-case this situation so that we can actually answer queries.

**Comment by jdr0887** [comment]
https://github.com/NCATS-Tangerine/cam-kp-api/blob/1981176009a75ea5ee5d46f991d3b63004974104/src/main/scala/org/renci/cam/Biolink.scala#L90

This is already in my trapi-1.1 branch.
