### ISSUE TITLE
align provenance output with current biolink-model approach

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#305]

**Comment by mmersmann** [comment]
Information source resolves to CAM-KP and graph name URI. Not sure whether this is what is expected. @jdr0887 to create a PR including a comment on provenance to verify what's in use is correct. If correct, this can be marked complete.

**Comment by mmersmann** [comment]
Provenance is there ("attribute_source": "infores:cam_kp"), but in need of a tweak to match what's in Matt Brush's spreadsheet.

**Comment by mmersmann** [comment]
See #373.

**Comment by balhoff** [comment]
Looks good now.
