### ISSUE TITLE
ensure we return KG edges using the canonical direction predicate for inverses

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#307]

**Comment by jdr0887** [comment]
I am still trying to understand this issue.  Does this mean that if we get a query with a predicate of "treats", then we should include results where we swap the subject & object using the "treated by" predicate?  Saying this another way...if the cam-kp is queried for "subject -> treats -> object", we should include results for the query of "object -> treated_by -> subject"?  If this is the case, then we would need a mapping of the inverses for each predicate...does that exist?

**Comment by balhoff** [comment]
We will already handle inverses as far as the query goes. This is all provided by the ontology semantics. So if we had a 'treats' edge we would always also have a 'treated by' edge. The main issue for us is when the query uses a general predicate, like 'related to', and our results are matching more specific predicates. If we return the result as 'related to', then no problem. But I think it is preferred to put the more specific result in the return message. And then we need to only return the results that use the canonical direction.

**Comment by balhoff** [comment]
Need to check our implementation to see if we output the most specific predicate, or the one that was queried (should be most specific).

**Comment by mmersmann** [comment]
@balhoff This is marked complete in the Architecture tracker. Is there any reason we shouldn't close this ticket?

**Comment by balhoff** [comment]
I think we can close.
