### ISSUE TITLE
Operations Exposed in Smart API Registry

### ISSUE THREAD

**Issue by mmersmann** [NCATS-Tangerine/cam-kp-api#344]
**Architecture Timeline: Due July 22**

References:
1. Associated Architecture Git ticket [here](https://github.com/NCATSTranslator/TranslatorArchitecture/issues/53).

**Comment by mmersmann** [comment]
**Action:** @jdr0887 to connect with @patrickkwang to get information for moving forward.

**Comment by jdr0887** [comment]
Here is a list of the operations:

https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/docs/index.md

**Comment by mmersmann** [comment]
SmartAPI tags list operations. Only operation relevant for us is "lookup" for which Jason has created a PR.
