### ISSUE TITLE
add predicates endpoint

### ISSUE THREAD

**Issue by jdr0887** [NCATS-Tangerine/cam-kp-api#49]
https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/TranslatorReasonersAPI.yaml

This page indicates that 2 services should be available: query and predicates.  The latter is a GET method.

**Comment by balhoff** [comment]
I'll take this on; it might be a chance to put in an example of the `sparql""` interpolator.

**Comment by balhoff** [comment]
This was completed, see #146.
